<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LNLA020P3014" name="org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL" tests="8" failures="1" timestamp="19 Jun 2018 12:27:23 GMT" time="131.966" errors="7">
  <testcase name="Step00_Prerequisite" time="131.966" classname="org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL">
    <failure type="java.lang.AssertionError" message="[Assertion Failed] : Element &#039;img_applicationLogo&#039; is Not Displayed in DOM expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: [Assertion Failed] : Element 'img_applicationLogo' is Not Displayed in DOM expected [1] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.ieee.standards.automation.getpageobjects.GetPage._intelligentAssertEquals(GetPage.java:226)
	at org.ieee.standards.automation.getpageobjects.GetPage._isElementDisplayed(GetPage.java:242)
	at org.ieee.standards.automation.getpageobjects.GetPage.isElementDisplayed(GetPage.java:653)
	at org.ieee.standards.RegAuthUDI.keywords.AppHomePageActions.verifyWhetherUserIsOnAppHomePage(AppHomePageActions.java:25)
	at org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL.Step00_Prerequisite(RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Step00_Prerequisite -->
  <testcase name="Step07_logoutFrom_Application" time="0.000" classname="org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL">
    <error type="java.lang.Throwable" message="Method RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL.Step07_logoutFrom_Application()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL@27efef64] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL.Step07_logoutFrom_Application()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL@27efef64] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Step07_logoutFrom_Application -->
  <testcase name="Step01_Launch_Application_And_Login_As_Admin" time="0.000" classname="org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL">
    <error type="java.lang.Throwable" message="Method RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL.Step01_Launch_Application_And_Login_As_Admin()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL@27efef64] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL.Step01_Launch_Application_And_Login_As_Admin()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL@27efef64] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Step01_Launch_Application_And_Login_As_Admin -->
  <testcase name="Step02_SelectThe_MALRegistryOrder" time="0.000" classname="org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL">
    <error type="java.lang.Throwable" message="Method RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL.Step02_SelectThe_MALRegistryOrder()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL@27efef64] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL.Step02_SelectThe_MALRegistryOrder()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL@27efef64] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Step02_SelectThe_MALRegistryOrder -->
  <testcase name="Step03_WorkOnConfidentialityStatus_OfSelectedRegistryOrder" time="0.000" classname="org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL">
    <error type="java.lang.Throwable" message="Method RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL.Step03_WorkOnConfidentialityStatus_OfSelectedRegistryOrder()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL@27efef64] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL.Step03_WorkOnConfidentialityStatus_OfSelectedRegistryOrder()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL@27efef64] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Step03_WorkOnConfidentialityStatus_OfSelectedRegistryOrder -->
  <testcase name="Step06_VerifyThe_AssignmentFormat" time="0.000" classname="org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL">
    <error type="java.lang.Throwable" message="Method RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL.Step06_VerifyThe_AssignmentFormat()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL@27efef64] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL.Step06_VerifyThe_AssignmentFormat()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL@27efef64] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Step06_VerifyThe_AssignmentFormat -->
  <testcase name="Step05_OperationOn_OrderStatus_OfRegistryOrder" time="0.000" classname="org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL">
    <error type="java.lang.Throwable" message="Method RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL.Step05_OperationOn_OrderStatus_OfRegistryOrder()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL@27efef64] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL.Step05_OperationOn_OrderStatus_OfRegistryOrder()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL@27efef64] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Step05_OperationOn_OrderStatus_OfRegistryOrder -->
  <testcase name="Step04_OperationOn_PaymenetStatus_OfRegistryOrder" time="0.000" classname="org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL">
    <error type="java.lang.Throwable" message="Method RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL.Step04_OperationOn_PaymenetStatus_OfRegistryOrder()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL@27efef64] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL.Step04_OperationOn_PaymenetStatus_OfRegistryOrder()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL@27efef64] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Step04_OperationOn_PaymenetStatus_OfRegistryOrder -->
</testsuite> <!-- org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC006_AdminGeneratingTheAssignmentID_MAL -->
