<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LNLA020P3014" name="org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status" tests="5" failures="0" timestamp="25 Jun 2018 09:48:34 GMT" time="0.008" errors="5">
  <testcase name="Step01_Launch_Application_And_Login_As_Requester" time="0.000" classname="org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status">
    <error type="java.lang.Throwable" message="Method RegAuthUDI_TC001_Active_contact_status.Step01_Launch_Application_And_Login_As_Requester()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status@59f99ea] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegAuthUDI_TC001_Active_contact_status.Step01_Launch_Application_And_Login_As_Requester()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status@59f99ea] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Step01_Launch_Application_And_Login_As_Requester -->
  <testcase name="Step04_logoutFrom_Application" time="0.000" classname="org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status">
    <error type="java.lang.Throwable" message="Method RegAuthUDI_TC001_Active_contact_status.Step04_logoutFrom_Application()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status@59f99ea] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegAuthUDI_TC001_Active_contact_status.Step04_logoutFrom_Application()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status@59f99ea] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Step04_logoutFrom_Application -->
  <testcase name="Step03_navigate_toAssignmentTab_And_VerfiyCompanies_AllAssignment" time="0.000" classname="org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status">
    <error type="java.lang.Throwable" message="Method RegAuthUDI_TC001_Active_contact_status.Step03_navigate_toAssignmentTab_And_VerfiyCompanies_AllAssignment()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status@59f99ea] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegAuthUDI_TC001_Active_contact_status.Step03_navigate_toAssignmentTab_And_VerfiyCompanies_AllAssignment()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status@59f99ea] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Step03_navigate_toAssignmentTab_And_VerfiyCompanies_AllAssignment -->
  <testcase name="Step00_Prerequisite" time="0.008" classname="org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status">
    <error type="org.yaml.snakeyaml.scanner.ScannerException" message="while scanning a simple key
 in &#039;reader&#039;, line 111, column 1:
    RegAuthUDI_TC008_ApplyingAddress ... 
    ^
could not find expected &#039;:&#039;
 in &#039;reader&#039;, line 112, column 20:
     OrganizationSearch: &quot;Automation&quot;
                       ^
">
      <![CDATA[while scanning a simple key
 in 'reader', line 111, column 1:
    RegAuthUDI_TC008_ApplyingAddress ... 
    ^
could not find expected ':'
 in 'reader', line 112, column 20:
     OrganizationSearch: "Automation"
                       ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465)
	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:393)
	at org.ieee.standards.automation.utils.YamlReader.getValue(YamlReader.java:106)
	at org.ieee.standards.automation.utils.YamlReader.getYamlValue(YamlReader.java:74)
	at org.ieee.standards.automation.utils.YamlReader.getData(YamlReader.java:78)
	at org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status.initVars(RegAuthUDI_TC001_Active_contact_status.java:33)
	at org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status.start_test_Session(RegAuthUDI_TC001_Active_contact_status.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Step00_Prerequisite -->
  <testcase name="Step02_navigate_toContactTab_And_VerfiyCompanies_ListedContact" time="0.000" classname="org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status">
    <error type="java.lang.Throwable" message="Method RegAuthUDI_TC001_Active_contact_status.Step02_navigate_toContactTab_And_VerfiyCompanies_ListedContact()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status@59f99ea] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegAuthUDI_TC001_Active_contact_status.Step02_navigate_toContactTab_And_VerfiyCompanies_ListedContact()[pri:0, instance:org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status@59f99ea] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Step02_navigate_toContactTab_And_VerfiyCompanies_ListedContact -->
</testsuite> <!-- org.ieee.standards.RegAuthUDI.tests.RegAuthUDI_TC001_Active_contact_status -->
